// <auto-generated />
using MVC_D2_Employee_DeptSystsem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_D2_Employee_DeptSystsem.Migrations
{
    [DbContext(typeof(SystemContext))]
    partial class SystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_D2_Employee_DeptSystsem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "Event Operation"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentName = "R&D"
                        });
                });

            modelBuilder.Entity("MVC_D2_Employee_DeptSystsem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("Dept_ID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("Dept_ID");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Dept_ID = 1,
                            EmployeeName = "ahmed"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Dept_ID = 1,
                            EmployeeName = "ayman"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Dept_ID = 2,
                            EmployeeName = "mohammed"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Dept_ID = 3,
                            EmployeeName = "mahmoud"
                        });
                });

            modelBuilder.Entity("MVC_D2_Employee_DeptSystsem.Models.Employee", b =>
                {
                    b.HasOne("MVC_D2_Employee_DeptSystsem.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Dept_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC_D2_Employee_DeptSystsem.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
